version: '3'
services:
  elasticsearch:
    image: bitergia/elasticsearch:6.1.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - esnet

  mariadb:
    image: mariadb:10.0
    command: --wait_timeout=2592000 --interactive_timeout=2592000 --max_connections=300
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    networks:
      - esnet

  kibiter:
    image: bitergia/kibiter:6.1.0-optimized
    ports:
      - "5601:5601"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.4"
          memory: 256M
      restart_policy:
        condition: on-failure
    environment:
      - ELASTICSEARCH_USER=bitergia
      - ELASTICSEARCH_PASSWORD=bitergia
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - NODE_OPTIONS=--max-old-space-size=1200
    networks:
      - esnet

  redis:
    image: redis:latest
    deploy:
      placement:
        constraints: [node.role == manager]
    volumes:
      - "/home/docker/data:/data"
    command: redis-server --save "" --appendonly no
    networks:
      - esnet

  arthur:
    image: acsdocker/arthur
    networks:
      - esnet

  mordred:
    image: bitergia/mordred:18.04-04
    environment:
      - SLEEP_LENGTH=30
    volumes:
      - ${PWD}/mytoken.cfg:/override.cfg
      - ${PWD}/mordred-infra.cfg:/infra.cfg
      - ${PWD}/mordred-project.cfg:/project.cfg
      - ${PWD}/mordred-dashboard.cfg:/dashboard.cfg
      - ${PWD}/projects.json:/projects.json
      - ${PWD}/identities.yaml:/identities.yaml
      - ${PWD}/menu.yaml:/home/bitergia/menu.yaml
      - ${PWD}/logs:/logs
    entrypoint: [ "/usr/local/bin/mordred" ]
    command: [ "-c", "/infra.cfg", "/dashboard.cfg", "/project.cfg", "/override.cfg"]
    networks:
      - esnet

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - esnet

networks:
  esnet:
